service: sls-test-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: go1.x
  region: ap-south-1


functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: /hello
          method: get
  ask:
    handler: bin/ask
    events:
      - http:
          path: /ask
          method: post
          cors: true
