service: sls-test-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: go1.x


functions:
  hello:
    handler: bin/hello
    events:
      - httpApi:
          path: /hello
          method: get
